name: ci-pr-verify
on:
  pull_request:
    types:
      - assigned
      - opened
      - synchronize
      - reopened

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Run Unit Tests
        run: ./gradlew clean test

      - name: Run Checkstyle Main
        run: ./gradlew checkstyleMain

      - name: Run Checkstyle Test
        run: ./gradlew checkstyleTest